### ISSUE TITLE
"AttributeError: module 'run' has no attribute 'Run'" while running MakeInstall.bat

### ISSUE THREAD

**Issue by Blazero** [corpnewt/gibMacOS#101]
Verifying OS name...
 - Name = NT
Verifying OS version...
 - Version = 18362

18362 >= 9600, continuing...
Traceback (most recent call last):
  File "D:\raison\Documents\Projects\gibMacOS\MakeInstall.py", line 863, in <module>
    w = WinUSB()
  File "D:\raison\Documents\Projects\gibMacOS\MakeInstall.py", line 16, in __init__
    self.d = diskwin.Disk()
  File "D:\raison\Documents\Projects\gibMacOS\Scripts\diskwin.py", line 8, in __init__
    self.r = run.Run()
AttributeError: module 'run' has no attribute 'Run'

**Comment by YunchaoZheng** [comment]
the same error too

**Comment by corpnewt** [comment]
Check [here](https://github.com/corpnewt/gibMacOS/issues/21).

-CorpNewt

**Comment by YunchaoZheng** [comment]
problem solved, thanks !!! using Anaconda too

**Comment by Blazero** [comment]
> 
> 
> Check [here](https://github.com/corpnewt/gibMacOS/issues/21).
> 
> -CorpNewt

I changed the file name and the import statements then it works. 
Maybe you can change them in the repository to aviod conflicts? So that no work needs to be done by the users.

**Comment by corpnewt** [comment]
I may go through and do that - but I've got 60-some repos and many of them use the same py modules, and I'm not sure when I'd have the time.  It would be *best* if Anaconda didn't add global modules, but I don't have control there.

-CorpNewt

**Comment by YunchaoZheng** [comment]
i suggest you add some codes to create and activate a pure python env before install , i don't know whether it will help but worth a try

**Comment by imwuwei** [comment]
In the third line of "Scripts/diskwin.py", import the "run" module. It looks normal because there is also a "run.py" in the "Scripts" directory. I think the author wants to import this file. If the "run" module is installed in python, it will conflict with the system module, and python will not directly import "Scripts/run.py". We should modify the "import run" in the third line of the "Scripts/diskwin.py" file to "from Scripts import run"
