### ISSUE TITLE
Error running MakeInstall.bat

### ISSUE THREAD

**Issue by LeongMY** [corpnewt/gibMacOS#104]
#######################################################
 #                Installing OpenCore                  #
#######################################################

Gathering info...
 - Got OpenCore-0.5.8-RELEASE.zip
Downloading...
Downloaded 1.97 MB of 1.97 MB (100.00%)
Extracting OpenCore-0.5.8-RELEASE.zip...
Gathering DUET boot files...
 - boot
 - boot0
 - boot1f32
Copying EFI folder to F:/EFI...
Copying boot to F:/boot...
Traceback (most recent call last):
  File "D:\OC-download\gMac\MakeInstall.py", line 882, in <module>
    w.main()
  File "D:\OC-download\gMac\MakeInstall.py", line 877, in main
    self.diskpart_erase(selected_disk, use_gpt, clover_version)
  File "D:\OC-download\gMac\MakeInstall.py", line 309, in diskpart_erase
    self.select_package(disk, clover_version)
  File "D:\OC-download\gMac\MakeInstall.py", line 405, in select_package
    self.dd_image(disk, os.path.join(temp, hfs), clover_version)
  File "D:\OC-download\gMac\MakeInstall.py", line 443, in dd_image
    if clover_version == "OpenCore": self.install_oc(disk)
  File "D:\OC-download\gMac\MakeInstall.py", line 515, in install_oc
    shutil.copy(os.path.join(temp,self.oc_boot),"{}/boot".format(part))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\tmp5i8q8g8m\\boot'

**Comment by corpnewt** [comment]
It seems acidanthera moved the DuetPkg files again - I'll see if I can figure out where they are now and update the script accordingly.

-CorpNewt

**Comment by corpnewt** [comment]
Should be updated as of [this commit](https://github.com/corpnewt/gibMacOS/commit/ef6fbe9ee40f8119968fe5f8bb26fefd1d928131).

-CorpNewt

**Comment by makewheels** [comment]
I think maybe should modify here too,
at MakeInstall.bat,line 33:

self.oc_boot = "Utilities/LegacyBoot/boot"
self.oc_boot0 = "Utilities/LegacyBoot/boot0"
self.oc_boot1 = "Utilities/LegacyBoot/boot1f32"

**Comment by makewheels** [comment]
But then pop up MyGetFileSIize

**Comment by StephenYangjz** [comment]
> I think maybe should modify here too,
> at MakeInstall.bat,line 33:
> 
> self.oc_boot = "Utilities/LegacyBoot/boot"
> self.oc_boot0 = "Utilities/LegacyBoot/boot0"
> self.oc_boot1 = "Utilities/LegacyBoot/boot1f32"
Im running into the same issue. Reading through the codes I feel like u r right. Did you make it? Is it a Windows issue or sth

**Comment by OneNYBoi** [comment]
I also have this problem
