### ISSUE TITLE
GibMacOS crashes when script is invoked from outside directory

### ISSUE THREAD

**Issue by sartbimpson** [corpnewt/gibMacOS#110]
# Expected Behavior

* Command `./gibMacOS/gibMacOS.command` should complete download of one version and go back to main menu

# Actual Behavior

* Command `./gibMacOS/gibMacOS.command` completes one download and crashes before reaching main menu

## Traceback

```
Traceback (most recent call last):

  File "./gibMacOS/gibMacOS.command", line 581, in <module>
    g.main(args.dmg)
  File "./gibMacOS/gibMacOS.command", line 477, in main
    self.download_prod(self.mac_prods[menu-1], dmg)
  File "./gibMacOS/gibMacOS.command", line 251, in download_prod
    os.chdir(os.path.dirname(os.path.realpath(__file__)))
OSError: [Errno 2] No such file or directory: '/Users/travis/build/[redacted]/[redacted]/misc/gibMacOS/gibMacOS'
```

**Comment by sartbimpson** [comment]
Also, thanks for making gibMacOS, it's really neat 👍
