### ISSUE TITLE
Error running MakeInstall.bat

### ISSUE THREAD

**Issue by ocfox** [corpnewt/gibMacOS#130]
Couldn't locate ddrelease64.exe - downloading...
 - Extracting...
Traceback (most recent call last):
  File "D:\Download\gibMacOS-master\MakeInstall.py", line 878, in <module>
    w.main()
  File "D:\Download\gibMacOS-master\MakeInstall.py", line 732, in main
    if not self.check_dd():
  File "D:\Download\gibMacOS-master\MakeInstall.py", line 114, in check_dd
    with zipfile.ZipFile(os.path.join(temp,z_file)) as z:
  File "C:\Users\Sunsky\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Sunsky\\AppData\\Local\\Temp\\tmpb8xn9m_t\\ddrelease64.exe.zip'

Script exited with error code: 1

**Comment by sunsky03** [comment]
It worked when I used this program yesterday. But there was an error today.

**Comment by oylinv** [comment]
> It worked when I used this program yesterday. But there was an error today.

it ok in the morning but not in the afternoon. so sad.
