### ISSUE TITLE
AttributeError: module 'run' has no attribute 'Run'

### ISSUE THREAD

**Issue by a-iarrocheski** [corpnewt/gibMacOS#137]
```
Traceback (most recent call last):
  File "C:\Users\Random\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 877, in <module>
    w = WinUSB()
  File "C:\Users\Random\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 16, in __init__
    self.d = diskwin.Disk()
  File "C:\Users\Random\Downloads\gibMacOS-master\gibMacOS-master\Scripts\diskwin.py", line 8, in __init__
    self.r = run.Run()
AttributeError: module 'run' has no attribute 'Run'

Script exited with error code: 1
```

**Comment by a-iarrocheski** [comment]
.
