### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by pigpp0103** [corpnewt/gibMacOS#155]
Extracting OpenCore-0.6.0-RELEASE.zip...
Gathering DUET boot files...
 - boot
 - boot0
 - boot1f32
Copying EFI folder to H:/EFI...
Copying boot to H:/boot...
Traceback (most recent call last):
  File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 879, in <module>
    w.main()
  File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 874, in main
    self.diskpart_erase(selected_disk, use_gpt, clover_version)
  File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 310, in diskpart_erase
    self.select_package(disk, clover_version)
  File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 406, in select_package
    self.dd_image(disk, os.path.join(temp, hfs), clover_version)
  File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 444, in dd_image
    if clover_version == "OpenCore": self.install_oc(disk)
  File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 516, in install_oc
    shutil.copy(os.path.join(temp,self.oc_boot),"{}/boot".format(part))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpdkrkc1l1\\boot'

Script exited with error code: 1

Press [enter] to exit...

**Comment by ZKBL** [comment]
> Extracting OpenCore-0.6.0-RELEASE.zip...
> Gathering DUET boot files...
> 
> * boot
> * boot0
> * boot1f32
>   Copying EFI folder to H:/EFI...
>   Copying boot to H:/boot...
>   Traceback (most recent call last):
>   File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 879, in 
>   w.main()
>   File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 874, in main
>   self.diskpart_erase(selected_disk, use_gpt, clover_version)
>   File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 310, in diskpart_erase
>   self.select_package(disk, clover_version)
>   File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 406, in select_package
>   self.dd_image(disk, os.path.join(temp, hfs), clover_version)
>   File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 444, in dd_image
>   if clover_version == "OpenCore": self.install_oc(disk)
>   File "D:\黑苹果\gibMacOS-master\MakeInstall.py", line 516, in install_oc
>   shutil.copy(os.path.join(temp,self.oc_boot),"{}/boot".format(part))
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 415, in copy
>   copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 261, in copyfile
>   with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
>   FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\ADMINI~1\AppData\Local\Temp\tmpdkrkc1l1\boot'
> 
> Script exited with error code: 1
> 
> Press [enter] to exit...

猜你是个中国人，是因为中国的网络问题，导致boot文件没下载成功，挂代理可以解决
