### ISSUE TITLE
Doesn't seem to work well with Anaconda

### ISSUE THREAD

**Issue by cassova** [corpnewt/gibMacOS#161]
I have Anaconda 2020.02 (tried also on 2019.10) with python 3.7.6.  When I would run this from a normal command prompt (as admin), it would give me an error: 

```
Traceback (most recent call last):
  File "C:\Temp\gibMacOS-master\MakeInstall.py", line 1, in <module>
    from Scripts import utils, diskwin, downloader, run
  File "C:\Temp\gibMacOS-master\Scripts\downloader.py", line 1, in <module>
    import sys, os, time, ssl
  File "C:\Users\mille\Anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified module could not be found.

Script exited with error code: 1

Press [enter] to exit...
```

When I would run it from my Anaconda command prompt (a shortcut which runs Anaconda3\Scripts\activate.bat), I would get this error:

```
#######################################################
 #                    Verifying OS                     #
#######################################################

Verifying OS name...
 - Name = NT
Verifying OS version...
 - Version = 18362

18362 >= 9600, continuing...
Traceback (most recent call last):
  File "C:\Temp\gibMacOS-master\MakeInstall.py", line 879, in <module>
    w = WinUSB()
  File "C:\Temp\gibMacOS-master\MakeInstall.py", line 16, in __init__
    self.d = diskwin.Disk()
  File "C:\Temp\gibMacOS-master\Scripts\diskwin.py", line 8, in __init__
    self.r = run.Run()
AttributeError: module 'run' has no attribute 'Run'

Script exited with error code: 1

Press [enter] to exit...
```

I solved my problem by opening a new normal command prompt same as first time and this time added python.exe to the PATH.  This strangely said it couldn't find python and asked to download which I confirmed.  After this was complete, I was able to get the menu.  Perhaps this is just me but it happened on two of my computers which are setup the same.

**Comment by Karatekid2407** [comment]
Same Problem here.

**Comment by br7roy** [comment]
I solve the Problem .
1. open Scrips\run.py
2. change line: 3 
```python
import run
# --------------> to
import Scripts.run as run
```
then runs ok.
