### ISSUE TITLE
MakeInstall.bat 

### ISSUE THREAD

**Issue by Felix660** [corpnewt/gibMacOS#167]
#######################################################
 #                    Verifying OS                     #
#######################################################

Verifying OS name...
 - Name = NT
Verifying OS version...
 - Version = 19041

19041 >= 9600, continuing...
Traceback (most recent call last):
  File "C:\Users\JAX\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 878, in <module>
    w = WinUSB()
  File "C:\Users\JAX\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 16, in __init__
    self.d = diskwin.Disk()
  File "C:\Users\JAX\Downloads\gibMacOS-master\gibMacOS-master\Scripts\diskwin.py", line 8, in __init__
    self.r = run.Run()
AttributeError: module 'run' has no attribute 'Run'

Script exited with error code: 1

Press [enter] to exit...

my Python is 3.8.3

**Comment by Felix660** [comment]
might be wrong with python in Anaconda

**Comment by Felix660** [comment]
sth wrong with 7zip, can't be download by cmd

**Comment by Felix660** [comment]
Now, only the last several steps, copy boot file and checking failed

**Comment by Neil-Dai** [comment]
I have the same problem！  don't know what is the matter with that

**Comment by rodrigolmacedo** [comment]
> 
> 
> sth wrong with 7zip, can't be download by cmd

you can edit makeinstall.py and put your own path to 7zip
'''
self.z_path64 = os.path.join("G:\\", "Programas", "7-Zip", "7z.exe")
'''

**Comment by gusgeek** [comment]
Could they fix it? I have the same problem...

**Comment by yuhuan-afk** [comment]
Try run it with Administrator permission.

**Comment by ThwinkoTun** [comment]
I have same problem, how to solve it please.
