### ISSUE TITLE
what's going on

### ISSUE THREAD

**Issue by jadderbao** [corpnewt/gibMacOS#257]
#######################################################
 #                Installing OpenCore                  #
#######################################################

Gathering info...
 - Got OpenCore-0.7.8-RELEASE.zip
Downloading...
Downloaded 5.76 MB of 5.76 MB (100.00%)
Extracting OpenCore-0.7.8-RELEASE.zip...
Gathering DUET boot files...
 - boot
 - boot0
 - boot1f32
Copying EFI folder to I:/EFI...
Copying boot to I:/boot...
Traceback (most recent call last):
  File "F:\iso\Mac OS X\gibMacOS-master\MakeInstall.py", line 879, in <module>
    w.main()
  File "F:\iso\Mac OS X\gibMacOS-master\MakeInstall.py", line 875, in main
    self.main()
  File "F:\iso\Mac OS X\gibMacOS-master\MakeInstall.py", line 874, in main
    self.diskpart_erase(selected_disk, use_gpt, clover_version)
  File "F:\iso\Mac OS X\gibMacOS-master\MakeInstall.py", line 310, in diskpart_erase
    self.select_package(disk, clover_version)
  File "F:\iso\Mac OS X\gibMacOS-master\MakeInstall.py", line 406, in select_package
    self.dd_image(disk, os.path.join(temp, hfs), clover_version)
  File "F:\iso\Mac OS X\gibMacOS-master\MakeInstall.py", line 444, in dd_image
    if clover_version == "OpenCore": self.install_oc(disk)
  File "F:\iso\Mac OS X\gibMacOS-master\MakeInstall.py", line 516, in install_oc
    shutil.copy(os.path.join(temp,self.oc_boot),"{}/boot".format(part))
  File "F:\tools\Python39\lib\shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "F:\tools\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jadder\\AppData\\Local\\Temp\\tmpsthhnfgu\\boot'

Script exited with error code: 1

Press [enter] to exit...

**Comment by leslie-DL** [comment]
same here,
our version of mac os is 001-68446 - 10.15.7 macOS Catalina
my options is Disk Number+o
