### ISSUE TITLE
Module run has no attribute Run

### ISSUE THREAD

**Issue by ExcelDude** [corpnewt/gibMacOS#44]
Hi, I ran into this strange error. 
Can you please advise. 

Thanks!

```python
#######################################################
 #                    Verifying OS                     #
#######################################################

Verifying OS name...
 - Name = NT
Verifying OS version...
 - Version = 17134

17134 >= 9600, continuing...
Traceback (most recent call last):
  File "C:\xxx\gibMacOS-master\MakeInstall.py", line 717, in <module>
    w = WinUSB()
  File "C:\xxx\gibMacOS-master\MakeInstall.py", line 12, in init
    self.d = diskwin.Disk()
  File "C:\xxx\gibMacOS-master\Scripts\diskwin.py", line 8, in init
    self.r = run.Run()
AttributeError: module 'run' has no attribute 'Run'
```

**Comment by corpnewt** [comment]
Discussed in [this issue] (https://github.com/corpnewt/gibMacOS/issues/32) already.  Has to do with a conflicting module in your python setup.

-CorpNewt
