### ISSUE TITLE
MakeInstall Script Error

### ISSUE THREAD

**Issue by Alee14** [corpnewt/gibMacOS#8]
Hey, so when I run MakeInstall.bat (as admin) this happened

```
Traceback (most recent call last):
  File "MakeInstall.py", line 773, in <module>
    w.main()
  File "MakeInstall.py", line 654, in main
    if not self.check_7z():
  File "MakeInstall.py", line 171, in check_7z
    return os.path.exists(self.z_path)
  File "C:\Users\Andrew Lee\AppData\Local\Programs\Python\Python37-32\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

Running Windows 10 October 2018 Update

Running Python 3.5

I do have 7zip installed

UPDATE: I had to put 7zip in my programs file in the c drive

**Comment by vuggg** [comment]
same error
