### ISSUE TITLE
makeinstall.bat exits with an error

### ISSUE THREAD

**Issue by Gizmo-Ger** [corpnewt/gibMacOS#81]
I´ve successfully downloaded the MacOS recovery but unfortunalety the makeinstall.bat crashes after marking the partition as active and a long pause. I´m not sure if it´s because I´m using a non-English version of Windows 10 or some other reason.

Exception in thread Thread-15:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python38\lib\subprocess.py", line 1366, in _readerthread
    buffer.append(fh.read())
ValueError: I/O operation on closed file.

DiskPart exited with non-zero status (2147755103).  Aborting.

**Comment by Sap1k** [comment]
Yep, I'm an Insider though
After a few tries it magically decided to work though. (much like anything I ever wrote xD)

**Comment by MateuszKrawczuk** [comment]
Problem always occurs when pendrive/drive is not first on list.

**Comment by florisdipt** [comment]
Same problem on windows 10 education N 
Build 14393.2906 Tried removing the whole volume(whole disk unassigned) and also tried reformatting partition to usb disk size.

Output:
`  #######################################################
 #               Erasing With DiskPart                 #
#######################################################

Using MBR...

Microsoft DiskPart version 10.0.14393.0

Copyright (C) 1999-2013 Microsoft Corporation.
On computer: DESKTOP-RV5TJDS

Disk 1 is now the selected disk.

DiskPart succeeded in cleaning the disk.

DiskPart successfully converted the selected disk to MBR format.

DiskPart succeeded in creating the specified partition.


    0 percent completed
    0 percent completed
    0 percent completed
  100 percent completed


DiskPart successfully formatted the volume.

DiskPart marked the current partition as active.

No usable free extent could be found. It may be that there is insufficient
free space to create a partition at the specified size and offset. Specify
different size and offset values or don't specify either to create the
maximum sized partition. It may be that the disk is partitioned using the MBR disk
partitioning format and the disk contains either 4 primary partitions, (no
more partitions may be created), or 3 primary partitions and one extended
partition, (only logical drives may be created).

DiskPart exited with non-zero status (2147942487).  Aborting.

Press [enter] to return...`

16 GB drive, tried rebooting and also other usb port all the same problem.

**Comment by pashenmebaojinwo** [comment]
![image](https://user-images.githubusercontent.com/43331024/88415522-352b0880-ce11-11ea-8fc1-641f22981967.png)
如何解决

**Comment by Felix660** [comment]
![image](https://user-images.githubusercontent.com/62864504/93738165-ade2f100-fc17-11ea-94a5-65d851f90ff3.png)

**Comment by Felix660** [comment]
same problem. don't know how
