### ISSUE TITLE
gibMacOS.bat Not running

### ISSUE THREAD

**Issue by JamesMoses** [corpnewt/gibMacOS#93]
```
Traceback (most recent call last):
  File "H:\---\macOS High Sierra 10.13.2 (17C88) [MultiRu] (Installer)\gibMacOS\gibMacOS-master\gibMacOS.command", line 543, in <module>
    g = gibMacOS()
  File "H:\---\macOS High Sierra 10.13.2 (17C88) [MultiRu] (Installer)\gibMacOS\gibMacOS-master\gibMacOS.command", line 7, in __init__
    self.d = downloader.Downloader()
NameError: name 'downloader' is not defined

H:\---\macOS High Sierra 10.13.2 (17C88) [MultiRu] (Installer)\gibMacOS\gibMacOS-master>
```

When running from command line it throws this error. When opening the .bat through Windows Explorer as admin, a command prompt window opens then swiftly disappears.

**Comment by JamesMoses** [comment]
SOLVED:

Running it on my C:\ drive worked.
